/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_zafu_opencv_OpenCVHelper */

#ifndef _Included_cn_edu_zafu_opencv_OpenCVHelper
#define _Included_cn_edu_zafu_opencv_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jintArray
JNICALL Java_opencv_opencv_OpenCVHelper_test(
        JNIEnv *env, jclass obj, jbyteArray srcy, jbyteArray srcu, jbyteArray srcv, int w, int h,
        jbyteArray toy, jbyteArray tou, jbyteArray tov) ;
#ifdef __cplusplus
}
#endif
#endif