/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_zafu_opencv_OpenCVHelper */

#ifndef _Included_cn_edu_zafu_opencv_OpenCVHelper
#define _Included_cn_edu_zafu_opencv_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_org_suirui_util_libyuv_jni_libYuvJNI_unLoadYuv(
		JNIEnv *env, jclass jcls);


// n21转420 sp 旋转 镜像处理
JNIEXPORT jbyteArray
JNICALL Java_org_suirui_util_libyuv_jni_libYuvJNI_nv21To420(JNIEnv *env, jclass obj, jbyteArray srcData, jint width, jint height,int rotate,jboolean isMirror,jboolean isRotate);

// 420转yuv分量
JNIEXPORT jobject
JNICALL Java_org_suirui_util_libyuv_jni_libYuvJNI_yuv420ToYUV(JNIEnv *env, jclass obj, jbyteArray srcData, jint width, jint height);

//NV21转I420并旋转
JNIEXPORT jbyteArray
JNICALL Java_org_suirui_util_libyuv_jni_libYuvJNI_NV21ToI420Rotate(JNIEnv *env, jclass obj, jbyteArray srcData,jint w, jint h,jint rotate);

//NV21转I420并旋转+镜像
    JNIEXPORT jbyteArray
    JNICALL Java_org_suirui_util_libyuv_jni_libYuvJNI_NV21ToI420RotateMirror(JNIEnv *env, jclass obj, jbyteArray srcData,jint w, jint h,jint rotate);
#ifdef __cplusplus
}
#endif
#endif